const PDFDocument = require('pdfkit');
const PptxGenJS = require('pptxgenjs');
const { Buffer } = require('buffer');

/**
 * Generate a PDF document from content
 * @param {string} title - Document title
 * @param {string} subtitle - Document subtitle
 * @param {array} sections - Array of {heading, content} objects
 * @returns {Promise<Buffer>} - PDF as buffer
 */
async function generatePDF(title, subtitle, sections) {
    return new Promise((resolve, reject) => {
        try {
            const doc = new PDFDocument({
                margin: 50,
                bufferPages: true
            });

            let chunks = [];
            doc.on('data', (chunk) => chunks.push(chunk));
            doc.on('end', () => {
                const pdfBuffer = Buffer.concat(chunks);
                resolve(pdfBuffer);
            });
            doc.on('error', reject);

            // Title page
            doc.fontSize(24).font('Helvetica-Bold').text(title, { align: 'center' });
            doc.moveDown(0.5);
            doc.fontSize(14).font('Helvetica').text(subtitle, { align: 'center' });
            doc.moveDown(2);

            // Add metadata
            doc.fontSize(10).fillColor('#666666').text(
                `Generated by SAGE AI on ${new Date().toLocaleDateString()}`,
                { align: 'center' }
            );
            doc.moveDown(2);

            // Reset color and font
            doc.fillColor('#000000').fontSize(11).font('Helvetica');

            // Add sections
            sections.forEach((section, index) => {
                // Section heading
                doc.fontSize(16).font('Helvetica-Bold').text(section.heading);
                doc.moveDown(0.5);

                // Section content
                doc.fontSize(11).font('Helvetica').text(section.content, {
                    align: 'left',
                    width: 500,
                    continued: false
                });
                doc.moveDown(1);

                // Add page break if needed (except for last section)
                if (index < sections.length - 1 && doc.y > 700) {
                    doc.addPage();
                }
            });

            // Footer
            doc.moveDown(1);
            doc.fontSize(9).fillColor('#999999').text(
                'This document was generated by SAGE AI - Your Business Development Assistant',
                { align: 'center' }
            );

            doc.end();
        } catch (error) {
            reject(error);
        }
    });
}

/**
 * Generate a PowerPoint presentation from content
 * @param {string} title - Presentation title
 * @param {string} subtitle - Presentation subtitle
 * @param {array} slides - Array of {title, bullets} objects
 * @returns {Promise<Buffer>} - PPTX as buffer
 */
async function generatePowerPoint(title, subtitle, slides) {
    try {
        const pres = new PptxGenJS();

        // Slide 1 - Title
        const slide1 = pres.addSlide();
        slide1.addText(title, {
            x: 0.5, y: 2.0, w: 9, h: 1,
            fontSize: 44, bold: true, color: '667eea'
        });
        slide1.addText(subtitle, {
            x: 0.5, y: 3.2, w: 9, h: 0.8,
            fontSize: 20, color: '764ba2'
        });

        // Content slides
        if (Array.isArray(slides)) {
            slides.forEach((slide, i) => {
                const contentSlide = pres.addSlide();
                contentSlide.addText(slide.title || `Slide ${i + 1}`, {
                    x: 0.5, y: 0.5, w: 9, h: 0.6,
                    fontSize: 28, bold: true, color: '667eea'
                });

                const content = Array.isArray(slide.bullets) 
                    ? slide.bullets.join('\n') 
                    : (slide.bullets || 'No content');
                    
                contentSlide.addText(content, {
                    x: 0.8, y: 1.3, w: 8.5, h: 4.8,
                    fontSize: 14, color: '333333'
                });
            });
        }

        const buffer = await pres.write({ type: 'buffer' });
        return buffer;
    } catch (error) {
        throw new Error(`PowerPoint generation error: ${error.message}`);
    }
}

function compileDocumentSections(topic, aiResponse) {
    // Create structured content for PDF by parsing AI response headers
    const pdfSections = [];
    
    // Add title/topic section
    pdfSections.push({
        heading: 'Executive Summary',
        content: `Topic: ${topic}\n\nThis document provides comprehensive insights generated dynamically based on your specific inquiry and proven business frameworks.`
    });

    let currentHeading = 'Detailed Analysis';
    let currentContent = [];

    // Parse markdown headers to create distinct sections
    const lines = aiResponse.split('\n');
    for (const line of lines) {
        if (line.match(/^#+\s+(.*)/)) {
            if (currentContent.length > 0 && currentContent.join('').trim().length > 0) {
                pdfSections.push({ heading: currentHeading, content: currentContent.join('\n').trim() });
                currentContent = [];
            }
            currentHeading = line.replace(/^#+\s+/, '').replace(/\*\*/g, '').trim();
        } else {
            // Remove bold and italic markdown markers as PDFKit handles plain text
            currentContent.push(line.replace(/\*\*/g, '').replace(/\*/g, ''));
        }
    }

    if (currentContent.length > 0 && currentContent.join('').trim().length > 0) {
        pdfSections.push({ heading: currentHeading, content: currentContent.join('\n').trim() });
    }

    // Add a dynamic next steps section
    pdfSections.push({
        heading: 'Next Steps',
        content: 'Connect with SAGE AI for personalized guidance on your specific situation. Use this document as a foundation for strategic decision-making.'
    });

    // Create structured content for PowerPoint (if ever enabled)
    const powerPointSlides = [
        {
            title: 'Key Takeaways',
            bullets: [
                'Strategic framework for ' + topic,
                'Based on proven business development methods',
                'Actionable steps for implementation'
            ]
        },
        {
            title: 'Strategic Approach',
            bullets: aiResponse.split('\n')
                .filter(line => line.trim().length > 0 && !line.startsWith('#'))
                .slice(0, 4)
                .map(line => line.replace(/\*\*/g, '').replace(/\*/g, '').substring(0, 100))
        }
    ];

    return { pdfSections, powerPointSlides };
}

/**
 * Generate and save documents (PDF only for now - PPT disabled)
 * @param {string} topic - Topic from user message
 * @param {string} aiResponse - AI-generated response
 * @returns {Promise<array>} - Array of resource objects
 */
async function generateDocuments(topic, aiResponse) {
    try {
        const { pdfSections, powerPointSlides } = compileDocumentSections(topic, aiResponse);
        
        // Generate only PDF for now (PowerPoint has library issue)
        const pdfBuffer = await generatePDF(
            topic, 
            'Business Development Guide',
            pdfSections
        );

        // Save to MongoDB as Resource document
        const Resource = require('../models/Resource');
        const timestamp = Date.now();
        const filename = `guide_${timestamp}.pdf`;

        const resource = new Resource({
            filename: filename,
            title: `${topic.substring(0, 60)} Guide`,
            description: `Auto-generated business development guide for: ${topic}`,
            category: 'Business Development',
            keywords: [topic, 'guide', 'strategy', 'development'],
            tags: ['auto-generated', 'pdf'],
            mimetype: 'application/pdf',
            size: pdfBuffer.length,
            data: pdfBuffer,
            isActive: true,
            isPublic: true
        });

        await resource.save();
        console.log(`✅ Generated PDF: ${filename} (${pdfBuffer.length} bytes)`);

        return [{
            id: resource._id,
            filename: resource.filename,
            title: resource.title,
            description: resource.description,
            fileType: 'pdf',
            size: resource.size,
            downloadUrl: `/api/resources/${resource._id}/download`
        }];
    } catch (error) {
        console.error('❌ Document generation error:', error.message);
        return [];
    }
}

module.exports = {
    generatePDF,
    generatePowerPoint,
    compileDocumentSections,
    generateDocuments
};
